name: Build CV

on:
  push:
    branches: [master]
    paths:
      - "template_2/**"
      - "modules/**"

jobs:
  build-cv:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup TeX Live
      uses: xu-cheng/latex-action@v3
      with:
        root_file: template_2/main.tex
        latexmk_use_xelatex: true
        work_in_root_file_dir: false

    - name: Commit generated PDF
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add template_2/out/main.pdf
        git diff --quiet && git diff --staged --quiet || (git commit -m "feat: auto-compile CV PDF [skip ci]" && git push)
