name: Auto-update README

on:
  push:
    branches: [ master ]
    paths:
      - 'attachments/output/*.png'
      - 'template_2/out/*.pdf'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Generate README
      run: |
        python scripts/generate_readme.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "docs(readme): auto-update README with latest CV images [skip ci]" && git push)
